name: Build & Publish Docker Image
on:
    release:
        types: [published]

jobs:
    push-to-dockerhub:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17
        steps:
            - name: Install Docker
              run: |
                apk update
                apk add docker docker-cli
                service docker start
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract Metadata
              id: metadata
              uses: docker/metadata-action@v4
              with:
                images: rvcaldwell/simple-node-api
                tags: |
                    type=semver, pattern={{version}}
                    type=semver, pattern={{major}}.{{minor}}
            - name: Build & Publish Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}
